### ISSUE TITLE
Publish jar on maven central

### ISSUE THREAD

**Issue by mfelsche** [harawata/appdirs#1]
Hello,
i am really missing a library like this for jvm development.
I am used to using the appdirs module in python.

Would you mind publishing this library as a jar to maven central or some comparable repository?

It would help us a lot!

**Comment by harawata** [comment]
Sure. Please give me some time.

Note that this library is not tested well enough, so you should test it thoroughly before deciding to use it 🙃

**Comment by harawata** [comment]
Published 1.0.0 to the central.

```xml
<dependency>
  <groupId>net.harawata</groupId>
  <artifactId>appdirs</artifactId>
  <version>1.0.0</version>
</dependency>
```

**Comment by mfelsche** [comment]
Awesome!!!
Thank you very much!

**Comment by harawata** [comment]
You're very welcome! =)
