### ISSUE TITLE
Temp Directory Support

### ISSUE THREAD

**Issue by erayerdin** [harawata/appdirs#3]
Each OS has different temp directory. It would be good to have such functionality.

**Comment by harawata** [comment]
In Java, you should use `System.getProperty("java.io.tmpdir")`. =)

**Comment by erayerdin** [comment]
Actually, yeah. Sorry for disturb. :smile: 
I leave closing the issue to you.

**Comment by harawata** [comment]
No problem. Thank you for taking the time to write a request. :)
