### ISSUE TITLE
ConfigDir on MacOSX

### ISSUE THREAD

**Issue by flsobral** [harawata/appdirs#34]
Shouldn't it point to Library/Preferences instead of Library/Application Support?

Since the preferences folder isn't removed when the application is uninstalled and can be migrated when upgrading the Mac, I think it makes sense to store user configuration inside this folder instead of Application Support, that is also available using DataDir.

**Comment by harawata** [comment]
Hello @flsobral ,

It seems that the original python module made the suggested change a while ago.
https://github.com/ActiveState/appdirs/pull/100

I'll make the change and release 1.2.0.
Thank you for taking the time to report!

**Comment by harawata** [comment]
@flsobral ,

1.2.0 is published on the [Maven Central](https://mvnrepository.com/artifact/net.harawata/appdirs) (it's not listed ATM, but it will be) and the [release page](https://github.com/harawata/appdirs/releases/tag/appdirs-1.2.0).
Thanks again for your contribution!
