### ISSUE TITLE
Support for Windows Server (2016)

### ISSUE THREAD

**Issue by Strohgelaender** [harawata/appdirs#38]
Calling `appDirs.getUserDataDir()` throws an Exception on Windows Server 2016 (and maybe other versions of Windows Server):

```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.sun.jna.platform.win32.Shell32.<clinit>(Shell32.java:32)
        at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:44)
        at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:61)
        at net.harawata.appdirs.impl.ShellFolderResolver.resolveFolder(ShellFolderResolver.java:47)
        at net.harawata.appdirs.impl.WindowsAppDirs.getLocalAppData(WindowsAppDirs.java:75)
        at net.harawata.appdirs.impl.WindowsAppDirs.getUserDataDir(WindowsAppDirs.java:33)
        at net.harawata.appdirs.AppDirs.getUserDataDir(AppDirs.java:20)
```

I was able to reproduce this exception on a new clean VM with just a Test-Application only calling this method. I tested with Java 9 and Java 14, both have the same Issue. I'm using the latest 1.2.0-Version.

On my Windows 10 System everything works fine.

**Comment by harawata** [comment]
Hello @Strohgelaender ,

The error says that JNA (which is a required dependency) does not exist in the classpath.
There should be files named `jna-platform-5.6.0.jar` and `jna-5.6.0.jar` usually in the same directory as `appdirs-1.2.0.jar`.
You can download these files from their repo : https://github.com/java-native-access/jna#download
Also, you should remove older versions if they exist.

I would appreciate if someone who has Windows Server environment could confirm whether AppDirs works or not. :)

**Comment by Strohgelaender** [comment]
Thank you for that quick response.

I'm not working with dependent -jar-Files, I'm using Maven to build my .jar. I checked this file and it seems to contain the jna-dependency (The folder com/sun/jna exists and it also contains a Native.class file)

As I said before, the same .jar works fine on a normal Windows 10 System. If it's really a dependency issue, then this Exception should be here the case either. But here everything works fine, the Exception occurs after transferring the same .jar-File into the Windows Server VM.

**Comment by harawata** [comment]
If the JAR is the same, there probably is something different with the loader.

- How do you run/deploy the jar? (servlet container? java -jar command?)
- Also, assuming you built a fat-jar (a.k.a. uber-jar), which maven plugin did you use to build it? (maven-shade-plugin, spring-boot-maven-plugin, etc.)

**Comment by Strohgelaender** [comment]
- I just type java -jar jarname.jar. I'm running the same Java Version on both systems: openjdk 14.0.2 2020-07-14
- The jar gets build with the maven-shade-plugin. Because the whole Application is a Spring Boot Application, it is configurated as it follows:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>3.2.2</version>
	<executions>
		<execution>
			<id>build-generic-jar</id>
			<phase>package</phase>
			<goals>
				<goal>shade</goal>
			</goals>
					<configuration>
				<outputFile>${project.basedir}/dist/${project.version}.jar
				</outputFile>
				<transformers>
					<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
						<manifestEntries>
							<Main-Class>my.package.AppDirTest</Main-Class>
						</manifestEntries>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.handlers</resource>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.schemas</resource>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.factories</resource>						</transformer>
				</transformers>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by harawata** [comment]
Thanks for the info, @Strohgelaender .

I would suggest a few tests.

The first test is to run the following Java app with non-fat JARs on the Windows Server.

```java
import com.sun.jna.platform.win32.KnownFolders;
import com.sun.jna.platform.win32.Shell32Util;

public class JnaTest {
  public static void main(String[] args) {
    System.out.println(Shell32Util.getKnownFolderPath(KnownFolders.FOLDERID_LocalAppData));
  }
}
```

1. save the above code as `JnaTest.java` and `copy jna-5.6.0.jar` and `jna-platform-5.6.0.jar` to the same directory
2. run the app.

```sh
java -cp jna-5.6.0.jar;jna-platform-5.6.0.jar;. JnaTest.java
```

If the test app outputs the path without throwing an exception...

1. replace the `appDirs.getUserDataDir()` call in your app with the above `Shell32Util.getKnownFolderPath()` call.
2. build the fat-Jar
3. run the fat-jar on the Windows Server

If one of the tests fails, please let me know the details.

**Comment by Strohgelaender** [comment]
The Test-Snippet just works as intended and gives me the correct path on the VM. ("C:\Users\Administrator\AppData\Local") Then I replaced the call in my app and tried executing the call now. The new .jar gives me a new Error-Message:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\jna-146731693\jna7635960561114601908.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
        at java.base/java.lang.Runtime.load0(Runtime.java:745)
        at java.base/java.lang.System.load(System.java:1871)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.Structure.<clinit>(Structure.java:2078)
        at com.sun.jna.platform.win32.KnownFolders.<clinit>(KnownFolders.java:20)
        at Test.main(Test.java:7)
```

I don't know what this should tell me know? Is there an issue with building the .jar-File? Or is the code looking for some dll that simply does not exist on Windows Server?

**Comment by harawata** [comment]
JNA uses a DLL to access native API and, according to their doc, it's auto-unpacked at runtime.
http://java-native-access.github.io/jna/5.6.0/javadoc/overview-summary.html#loading

And the test result shows that the problem occurs when unpacking the DLL or when loading the unpacked DLL.

I am not sure why it occurs only on Windows Server, but you should probably try building the fat-jar using the spring-boot-maven-plugin if you haven't.
Unlike maven-shade-plugin, it includes dependencies as JARs, so it could make a difference.

If it still didn't solve the problem, I would suggest posting a question to JNA's [mailing list](http://groups.google.com/group/jna-users) or [Stackoverflow](http://stackoverflow.com/questions/tagged/jna).
Someone who is familiar with JNA may have an answer.

**Comment by Strohgelaender** [comment]
wow, I did a really dumb mistake: I overlooked that somewhere in this huge pom.xml an older version of jna was added as a dependency, which contained this Windows Server Bug... Fixed this just by updating... Thanks for your help.
