### ISSUE TITLE
Cannot initialize logger appender 

### ISSUE THREAD

**Issue by Vistritium** [harawata/appdirs#4]
I'm using slf4j with logback. I created custom FileAppender and I wanted to select destination of log file using appdirs. Unfortunately the lib uses the logging itself so it became an circular dependency - my appender needs appdirs, appdirs needs logging and logging needs my appender. Not sure how to address this issue.

**Comment by harawata** [comment]
Thank you for the report, @Vistritium !

This is actually a SLF4J/Logback question and I am not sure how to solve it.
Why don't you ask it on their [mailing list](https://logback.qos.ch/mailinglist.html)?
As it seems like a common use case (i.e. a custom appender that uses another component which also uses SLF4J for logging), I'm pretty sure that you will get some answers if you show them your appender code.

**Comment by Vistritium** [comment]
Thanks for response.
Ok, I'll try to resolve issue looking around SLF4J/Logback.

**Comment by harawata** [comment]
In case someone find this issue...
This issue should be resolved in version 1.2.1.
