### ISSUE TITLE
AppDirs dosn't show up in Intellij idea

### ISSUE THREAD

**Issue by jack5505** [harawata/appdirs#52]
Hello !
Thank you for wonderfull library. But I can't make it work.
Firstly I added library into pom.xml of my project the latest version of library.

**
<dependency>
    <groupId>net.harawata</groupId>

    <artifactId>appdirs</artifactId>

    <version>1.2.1</version>
</dependency>**

But when I try to write into class this library my project dosn't see (I was wondering how).

<img width="682" alt="Снимок экрана 2021-09-07 в 12 37 02" src="https://user-images.githubusercontent.com/20322245/132303946-90aae577-c700-4b61-b208-58a80ae5d6e0.png">

When I pay attentiong that this library include of in maven but not showing in maven toolbar that has in intellij idea in left toolbar.

<img width="1472" alt="Снимок экрана 2021-09-07 в 12 37 49" src="https://user-images.githubusercontent.com/20322245/132304072-b0231e6a-4b90-4723-bd8f-2a3a6393dcae.png">

If you see below. You could see all dependecies that written in pom xml has in left toolbar but not AppDirs library. Please could you help me to figure it out about it. How I could make to show up this library in my project 

Thanks in advance

**Comment by harawata** [comment]
That's an IntelliJ issue. You should contact its support.
Some users are experiencing the same or similar problem, it seems.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003445760
